package com.likeminds.feedsx.utils.model

import androidx.annotation.IntDef

const val ITEM_NONE = 0
const val ITEM_POST_TEXT_ONLY = 1
const val ITEM_POST_SINGLE_IMAGE = 2
const val ITEM_POST_SINGLE_VIDEO = 3
const val ITEM_POST_DOCUMENTS = 4
const val ITEM_POST_LINK = 5
const val ITEM_POST_MULTIPLE_MEDIA = 6
const val ITEM_MULTIPLE_MEDIA_IMAGE = 7
const val ITEM_MULTIPLE_MEDIA_VIDEO = 8
const val ITEM_MEDIA_PICKER_FOLDER = 9
const val ITEM_MEDIA_PICKER_BROWSE = 12
const val ITEM_MEDIA_PICKER_HEADER = 13
const val ITEM_MEDIA_PICKER_SINGLE = 14
const val ITEM_MEDIA_PICKER_DOCUMENT = 15

@IntDef(
    ITEM_NONE,
    ITEM_POST_TEXT_ONLY,
    ITEM_POST_SINGLE_IMAGE,
    ITEM_POST_SINGLE_VIDEO,
    ITEM_POST_DOCUMENTS,
    ITEM_POST_LINK,
    ITEM_POST_MULTIPLE_MEDIA,
    ITEM_MULTIPLE_MEDIA_IMAGE,
    ITEM_MULTIPLE_MEDIA_VIDEO,
    ITEM_MEDIA_PICKER_FOLDER,
    ITEM_MEDIA_PICKER_BROWSE,
    ITEM_MEDIA_PICKER_HEADER,
    ITEM_MEDIA_PICKER_SINGLE,
    ITEM_MEDIA_PICKER_DOCUMENT
)
@Retention(AnnotationRetention.SOURCE)
annotation class ViewType